// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spot.Data;

namespace Spot.Data.Migrations
{
    [DbContext(typeof(SpotContext))]
    [Migration("20210908013023_ReservationStatusUpdate")]
    partial class ReservationStatusUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Spot.Common.Business", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ReservationsRequireApproval")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("OwnerUsername");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("Spot.Common.Reservation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SpotID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("SpotID");

                    b.HasIndex("Username");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Spot.Common.Spot", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BusinessID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BusinessID");

                    b.ToTable("Spot");
                });

            modelBuilder.Entity("Spot.Common.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Spot.Common.Business", b =>
                {
                    b.HasOne("Spot.Common.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUsername");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Spot.Common.Reservation", b =>
                {
                    b.HasOne("Spot.Common.Spot", "Spot")
                        .WithMany()
                        .HasForeignKey("SpotID");

                    b.HasOne("Spot.Common.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("Username");

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Spot.Common.Spot", b =>
                {
                    b.HasOne("Spot.Common.Business", "Business")
                        .WithMany("Spots")
                        .HasForeignKey("BusinessID");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Spot.Common.Business", b =>
                {
                    b.Navigation("Spots");
                });

            modelBuilder.Entity("Spot.Common.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
